name: self-httpserver-jwt-postgres

services:
  self-users-db:
    image: postgres
    container_name: self-users-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-self-users}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - dev.env
    networks:
      - "default"
    ports:
      - "${DB_USERS_PORT:-5432}:5432"

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: self-api
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - dev.env
    depends_on:
      self-users-db:
        condition: service_healthy
    networks:
      - "default"
    restart: unless-stopped